'use client'
import './globals.scss'

import { Providers } from "./providers"

import PageContainer from '@/components/PageContainer'
import { useProgress } from '@/hooks/useProgress'

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  useProgress()
  return (
    <html lang="en" suppressHydrationWarning={ true }>
      <body suppressHydrationWarning={ true }>
        <Providers>
          <PageContainer>
            { children }
          </PageContainer>
        </Providers>
      </body>
    </html>
  )
}